version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: teanetworks
      MYSQL_PASSWORD: teanetworks
      MYSQL_ROOT_PASSWORD: teanetworks